cms/urls.py
# coding: utf-8
from django.conf.urls import url
from django.contrib.auth import views

from .views import *

urlpatterns = [
    # 社内PC管理
    url(r'^$', pc_list, name='pc_list'),   # 一覧
    url(r'^detail/(?P<pc_id>\d+)/$', pc_detail, name='pc_detail'),  # 詳細
    url(r'^add/$', pc_edit, name='pc_add'),  # 登録
    url(r'^mod/(?P<pc_id>\d+)/$', pc_edit, name='pc_mod'),  # 修正
    url(r'^del/(?P<pc_id>\d+)/$', pc_del, name='pc_del'),   # 削除
    url(r'^save_sort/$', save_sort, name='save_sort'),   # ソート順保存
    url(r'^download/$', download, name='download'),  # エクセルダウンロード
    url(r'^upload/$', upload, name='upload'),  # エクセルアップロード
    url(r'^login/$', views.login,
        {'template_name': 'cms/login.html'}, name='login'),   # ログイン
    url(r'^logout/$', views.logout,
        {'template_name': 'cms/logout.html'}, name='logout')  # ログアウト
]

pc_management/urls.py
# coding: utf-8
"""pc_management URL Configuration.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.9/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))

"""
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('cms.urls', namespace='cms')),
]

cms/models/pc_management.py
# coding: utf-8
from django.db import models


class NullableCharField(models.CharField):
    __metaclass__ = models.SubfieldBase

    def to_python(self, value):
        if isinstance(value, models.CharField):
            return value
        return value or ''

    def get_prep_value(self, value):
        return value or None


class PC_Management(models.Model):

    MACHINE_TYPE_CHOICE = (
        (0, 'デスクトップ'),
        (1, 'ノートパソコン'),
    )
    ASSET_CLASS_CHOICE = (
        (0, '購入品'),
        (1, 'リース品'),
    )
    user = models.CharField('使用者', max_length=255, null=True)
    user_project = models.CharField(
        '使用プロジェクト', max_length=255, null=True, blank=True)
    storage_location = models.CharField(
        '保管場所', max_length=50, null=True, blank=True)
    machine_type = models.IntegerField(
        '種類', default=0, choices=MACHINE_TYPE_CHOICE, null=True)
    asset_class = models.IntegerField(
        '資産種類', default=0, choices=ASSET_CLASS_CHOICE, null=True)
    pc_number = models.CharField(
        'PC機器番号', max_length=255, null=True, unique=True)
    ip_address = NullableCharField(
        'IPアドレス', max_length=255, null=True, blank=True, unique=True)
    maker = models.CharField('メーカー', max_length=255, null=True)
    display_size = models.CharField(
        'ディスプレイ - サイズ', max_length=255, null=True, blank=True)
    display_number = NullableCharField(
        'ディスプレイ - 機器番号', max_length=255, null=True, blank=True, unique=True)
    keyboard_number = NullableCharField(
        'キーボード機器番号', max_length=255, null=True, blank=True, unique=True)
    mouth_number = NullableCharField(
        'マウス機器番号', max_length=255, null=True, blank=True, unique=True)
    os = models.CharField('OS', max_length=255, null=True)
    cpu = models.CharField('CPU', max_length=255, null=True)
    hdd_storage = models.CharField('HDD容量', max_length=255, null=True)
    memory_storage = models.CharField('メモリ容量', max_length=255, null=True)
    media_drive = models.CharField(
        'メディアドライブ', max_length=255, null=True, blank=True)
    lease_expiration_date = models.DateField(
        'リース期限日', max_length=255, null=True, blank=True)
    remarks = models.TextField('備考', null=True, blank=True)
    sort_no = models.IntegerField('ソートNo', unique=True)

    class Meta:
        verbose_name = '機器'
        verbose_name_plural = verbose_name

cms/forms.py
# coding: utf-8
from django import forms
from django.forms import ModelForm
from django.forms.widgets import DateInput, Select, Textarea, TextInput

from cms.models import PC_Management


class PC_ManagementForm(ModelForm):
    """PC追加編集フォーム."""
    class Meta:
        model = PC_Management
        fields = ('user', 'user_project', 'storage_location',
                  'machine_type', 'asset_class', 'pc_number', 'ip_address',
                  'maker', 'display_size', 'display_number', 'keyboard_number',
                  'mouth_number', 'os', 'cpu', 'hdd_storage', 'memory_storage',
                  'media_drive', 'lease_expiration_date', 'remarks', )
        widgets = {
            'user': TextInput(attrs={'size': 40}),
            'user_project': TextInput(attrs={'size': 40}),
            'lease_expiration_date': DateInput(attrs={'type': 'date'}),
        }


class PC_ReadOnlyForm(ModelForm):
    """PC閲覧専用フォーム."""
    class Meta:
        model = PC_Management
        fields = ('user', 'user_project', 'storage_location',
                  'machine_type', 'asset_class', 'pc_number', 'ip_address',
                  'maker', 'display_size', 'display_number', 'keyboard_number',
                  'mouth_number', 'os', 'cpu', 'hdd_storage', 'memory_storage',
                  'media_drive', 'lease_expiration_date', 'remarks', )
        widgets = {
            'sort_no': TextInput(attrs={'readonly': 'readonly'}),
            'user': TextInput(attrs={'size': 40, 'readonly': 'readonly'}),
            'user_project': TextInput(attrs={'size': 40, 'readonly': 'readonly'}),
            'storage_location': TextInput(attrs={'readonly': 'readonly'}),
            'machine_type': Select(attrs={'disabled': 'disabled'}),
            'asset_class': Select(attrs={'disabled': 'disabled'}),
            'pc_number': TextInput(attrs={'readonly': 'readonly'}),
            'ip_address': TextInput(attrs={'readonly': 'readonly'}),
            'maker': TextInput(attrs={'readonly': 'readonly'}),
            'display_size': TextInput(attrs={'readonly': 'readonly'}),
            'display_number': TextInput(attrs={'readonly': 'readonly'}),
            'keyboard_number': TextInput(attrs={'readonly': 'readonly'}),
            'mouth_number': TextInput(attrs={'readonly': 'readonly'}),
            'os': TextInput(attrs={'readonly': 'readonly'}),
            'cpu': TextInput(attrs={'readonly': 'readonly'}),
            'hdd_storage': TextInput(attrs={'readonly': 'readonly'}),
            'memory_storage': TextInput(attrs={'readonly': 'readonly'}),
            'media_drive': TextInput(attrs={'readonly': 'readonly'}),
            'lease_expiration_date': DateInput(attrs={'readonly': 'readonly', 'type': 'date', }, format=('%Y-%m-%d')),
            'remarks': Textarea(attrs={'readonly': 'readonly'}),
        }


class UploadFileForm(forms.Form):
    file = forms.FileField(label='Excel')

cms/views.py
# coding: utf-8
import datetime
import functools
import io
import os

import xlrd
import xlwt
import json
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.http import Http404, HttpResponse
from django.shortcuts import get_object_or_404, redirect, render

from cms.forms import PC_ManagementForm, PC_ReadOnlyForm, UploadFileForm
from cms.models import PC_Management
from django.db.models import Max


def render_json_response(request, data, status=None):
    json_obj = json.dumps(data, ensure_ascii=False, indent=2)
    return HttpResponse(json_obj,
                        content_type='application/json; charset=UTF-8',
                        status=status)


def user_permission():
    def preprocess(func):
        @functools.wraps(func)
        def wrapper(*args, **kwargs):
            # View の Request オブジェクトを取り出す
            request = args[0]
            # ユーザー権限を取得
            if not request.user.is_staff:
                raise Http404
            return func(*args, **kwargs)
        return wrapper
    return preprocess


@login_required
def pc_list(request):
    """PCの一覧."""
    pc_list = PC_Management.objects.all().order_by('sort_no')
    upload_form = UploadFileForm()
    return render(request,
                  'cms/pc_list.html',
                  {'pc_list': pc_list, 'upload_form': upload_form})


@login_required
def pc_detail(request, pc_id=None):
    """PCの詳細."""
    pc_detail = get_object_or_404(PC_Management, pk=pc_id)
    form = PC_ReadOnlyForm(instance=pc_detail)  # pc インスタンスからフォームを作成

    return render(request, 'cms/pc_detail.html', dict(form=form, pc_id=pc_id))


@login_required
@user_permission()
def pc_edit(request, pc_id=None):
    """PCの編集."""
    isCopy = request.GET.get('copy')
    if pc_id:  # pc_id が指定されている (修正時)
        pc = get_object_or_404(PC_Management, pk=pc_id)
        if isCopy:  # 複製の時は新規追加扱い
            pc.pk = None
            pc.id = None
    else:  # pc_id が指定されていない (追加時)
        pc = PC_Management()
    # 新規作成又は複製の時にソート番号を割り当てる
    if not pc_id or isCopy:
        pc.sort_no = PC_Management.objects.all().aggregate(
            Max('sort_no'))['sort_no__max'] + 1

    if request.method == 'POST':
        # POST された request データからフォームを作成
        form = PC_ManagementForm(request.POST, instance=pc)
        if form.is_valid():  # フォームのバリデーション
            pc = form.save(commit=False)
            pc.save()
            return redirect('cms:pc_list')
    else:  # GET の時
        form = PC_ManagementForm(instance=pc)  # pc インスタンスからフォームを作成

    return render(request, 'cms/pc_edit.html', dict(form=form, pc_id=pc_id, isCopy=isCopy))


@login_required
@user_permission()
def save_sort(request):
    """ソート"""
    ids = request.GET.getlist('ids[]')  # クエリーストリングの配列を取得
    res = {}    # id: sort_no
    for i, pk in enumerate(ids):
        pc = PC_Management.objects.get(pk=pk)
        pc.sort_no = i + 1
        pc.save()
        res.update({pc.id: pc.sort_no})
    return render_json_response(request, res, 200)


@login_required
@user_permission()
def pc_del(request, pc_id):
    """PCの削除."""
    pc = get_object_or_404(PC_Management, pk=pc_id)
    pc.delete()
    return redirect('cms:pc_list')


@login_required
@user_permission()
def download(request):
    output = io.BytesIO()

    wb = xlwt.Workbook()
    ws = wb.add_sheet('sheet 1')

    pc_list = PC_Management.objects.all().order_by('id')
    i = 0
    for pc in pc_list:
        if i == 0:
            ws.write(i, 0, '使用者')
            ws.write(i, 1, '使用プロジェクト')
            ws.write(i, 2, '保管場所')
            ws.write(i, 3, '種類(0:デスクトップパソコン 1:ノートパソコン)')
            ws.write(i, 4, '資産種類(0:購入品 1:リース品)')
            ws.write(i, 5, 'PC機器番号')
            ws.write(i, 6, 'IPアドレス')
            ws.write(i, 7, 'メーカー')
            ws.write(i, 8, 'ディスプレイ - サイズ')
            ws.write(i, 9, 'ディスプレイ - 機器番号')
            ws.write(i, 10, 'キーボード機器番号')
            ws.write(i, 11, 'マウス機器番号')
            ws.write(i, 12, 'OS')
            ws.write(i, 13, 'CPU')
            ws.write(i, 14, 'HDD容量')
            ws.write(i, 15, 'メモリ容量')
            ws.write(i, 16, 'メディアドライブ')
            ws.write(i, 17, 'リース期限日')
            ws.write(i, 18, '備考')
            i += 1
        ws.write(i, 0, pc.user)
        ws.write(i, 1, pc.user_project)
        ws.write(i, 2, pc.storage_location)
        ws.write(i, 3, pc.machine_type)
        ws.write(i, 4, pc.asset_class)
        ws.write(i, 5, pc.pc_number)
        ws.write(i, 6, pc.ip_address)
        ws.write(i, 7, pc.maker)
        ws.write(i, 8, pc.display_size)
        ws.write(i, 9, pc.display_number)
        ws.write(i, 10, pc.keyboard_number)
        ws.write(i, 11, pc.mouth_number)
        ws.write(i, 12, pc.os)
        ws.write(i, 13, pc.cpu)
        ws.write(i, 14, pc.hdd_storage)
        ws.write(i, 15, pc.memory_storage)
        ws.write(i, 16, pc.media_drive)
        ws.write(i, 17, pc.lease_expiration_date,
                 xlwt.easyxf(num_format_str='yyyy-mm-dd'))
        ws.write(i, 18, pc.remarks)
        i += 1
    wb.save(output)

    response = HttpResponse(
        output.getvalue(), content_type='application/excel')
    response['Content-Disposition'] = 'filename=pc_list.xls'
    return response


@login_required
@user_permission()
def upload(request):
    if request.method == 'POST':
        upload_form = UploadFileForm(request.POST, request.FILES)
        if upload_form.is_valid():
            excel_registration(request.FILES['file'])
            return redirect('cms:pc_list')
    else:
        return redirect('cms:pc_list')


def excel_registration(f):

    with open(settings.MEDIA_ROOT + '/' + f.name, 'wb+') as destination:
        for chunk in f.chunks():
            destination.write(chunk)

    with xlrd.open_workbook(settings.MEDIA_ROOT + '/' + f.name) as excel:

        for i in range(excel.nsheets):
            sheet = excel.sheet_by_index(i)
            for row in range(1, sheet.nrows):
                pc = PC_Management()
                pc.user = sheet.cell(row, 0).value
                pc.user_project = sheet.cell(row, 1).value
                pc.storage_location = sheet.cell(row, 2).value
                pc.machine_type = sheet.cell(row, 3).value
                pc.asset_class = sheet.cell(row, 4).value
                pc.pc_number = sheet.cell(row, 5).value
                pc.ip_address = sheet.cell(row, 6).value
                pc.maker = sheet.cell(row, 7).value
                pc.display_size = sheet.cell(row, 8).value
                pc.display_number = sheet.cell(row, 9).value
                pc.keyboard_number = sheet.cell(row, 10).value
                pc.mouth_number = sheet.cell(row, 11).value
                pc.os = sheet.cell(row, 12).value
                pc.cpu = sheet.cell(row, 13).value
                pc.hdd_storage = sheet.cell(row, 14).value
                pc.memory_storage = sheet.cell(row, 15).value
                pc.media_drive = sheet.cell(row, 16).value
                if sheet.cell(row, 17).value:
                    pc.lease_expiration_date = datetime.datetime(
                        *xlrd.xldate_as_tuple(sheet.cell(row, 17).value, excel.datemode))
                pc.remarks = sheet.cell(row, 18).value
                pc.save()
    os.remove(settings.MEDIA_ROOT + '/' + f.name)

cms/templates/cms/login.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block extrahead %}
<style>
.wrapper {
	margin-top: 80px;
	margin-bottom: 20px;
}

.form-signin {
  max-width: 420px;
  padding: 30px 38px 66px;
  margin: 0 auto;
  background-color: #eee;
  border: 3px dotted rgba(0,0,0,0.1);
  }

.form-signin-heading {
  text-align:center;
  margin-bottom: 30px;
}

.form-control {
  position: relative;
  font-size: 16px;
  height: auto;
  padding: 10px;
}

input[type="text"] {
  margin-bottom: 0px;
  border-bottom-left-radius: 0;
  border-bottom-right-radius: 0;
}

input[type="password"] {
  margin-bottom: 20px;
  border-top-left-radius: 0;
  border-top-right-radius: 0;
}

.colorgraph {
  height: 7px;
  border-top: 0;
  background: #c4e17f;
  border-radius: 5px;
  background-image: -webkit-linear-gradient(left, #c4e17f, #c4e17f 12.5%, #f7fdca 12.5%, #f7fdca 25%, #fecf71 25%, #fecf71 37.5%, #f0776c 37.5%, #f0776c 50%, #db9dbe 50%, #db9dbe 62.5%, #c49cde 62.5%, #c49cde 75%, #669ae1 75%, #669ae1 87.5%, #62c2e4 87.5%, #62c2e4);
  background-image: -moz-linear-gradient(left, #c4e17f, #c4e17f 12.5%, #f7fdca 12.5%, #f7fdca 25%, #fecf71 25%, #fecf71 37.5%, #f0776c 37.5%, #f0776c 50%, #db9dbe 50%, #db9dbe 62.5%, #c49cde 62.5%, #c49cde 75%, #669ae1 75%, #669ae1 87.5%, #62c2e4 87.5%, #62c2e4);
  background-image: -o-linear-gradient(left, #c4e17f, #c4e17f 12.5%, #f7fdca 12.5%, #f7fdca 25%, #fecf71 25%, #fecf71 37.5%, #f0776c 37.5%, #f0776c 50%, #db9dbe 50%, #db9dbe 62.5%, #c49cde 62.5%, #c49cde 75%, #669ae1 75%, #669ae1 87.5%, #62c2e4 87.5%, #62c2e4);
  background-image: linear-gradient(to right, #c4e17f, #c4e17f 12.5%, #f7fdca 12.5%, #f7fdca 25%, #fecf71 25%, #fecf71 37.5%, #f0776c 37.5%, #f0776c 50%, #db9dbe 50%, #db9dbe 62.5%, #c49cde 62.5%, #c49cde 75%, #669ae1 75%, #669ae1 87.5%, #62c2e4 87.5%, #62c2e4);
}
</style>
{% endblock %}

{% block content %}
<div class="wrapper">
    <form action="" method="post" name="Login_Form" class="form-signin">
        {% csrf_token %}
        <h3 class="form-signin-heading">社内PC管理ログイン</h3>
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
        ユーザー名とパスワードを正しく入力してください。
        </div>
        {% endif %}
        <hr class="colorgraph"><br>

        {{ form.username|attr:"class:form-control" }}
        {{ form.password|attr:"class:form-control" }}

         <input type="submit" value="ログイン" class="btn btn-lg btn-primary btn-block">
    </form>
</div>
{% endblock content %}

cms/templates/cms/logout.html
{% extends "base.html" %}
{% load bootstrap %}

{% block title %}ログアウト{% endblock title %}
{% block extrahead %}
<meta http-equiv="refresh" content="3;URL={% url 'cms:login' %}" />
{% endblock %}
{% block content %}

<h3 class="page-header">ログアウトしました</h3>
<p>3秒後にログインページへリダイレクトされます。</p>

{% endblock content %}

cms/templates/cms/pc_detail.html
{% extends "base_nav.html" %}
{% load bootstrap %}

{% block title %}PCの詳細{% endblock title %}
{% block extrahead %}
<style>
.form-control {
  width: initial !important;
}
</style>
{% endblock %}
{% block content %}
    <h3 class="page-header">PCの詳細</h3>
    <form action="" method="post" class="form-horizontal" role="form">
      {% csrf_token %}
      {{ form|bootstrap_horizontal }}
    </form>
    <a href="{% url 'cms:pc_list' %}" class="btn btn-default btn-sm">戻る</a>
{% endblock content %}

cms/templates/cms/pc_edit.html
{% extends "base_nav.html" %}
{% load bootstrap %}

{% block title %}PCの編集{% endblock title %}
{% block extrahead %}
<style>
.form-control {
  width: initial !important;
}
</style>
<script>
$(function(){
    if (!$("#id_display_size").val()) $("#id_display_number").prop("disabled", true);
    else $("#id_display_number").prop("disabled", false);

    if ($("[name=asset_class]").val() == 0) $("#id_lease_expiration_date").prop("disabled", true);
    else $("#id_lease_expiration_date").prop("disabled", false);

    $("#id_display_size").blur(function(){
        if($(this).val()) $("#id_display_number").prop("disabled", false);
        else{
            $("#id_display_number").prop("disabled", true);
            $("#id_display_number").val('');
        }
    });
    $("[name=asset_class]").change(function(){
        if($(this).val() == 1) $("#id_lease_expiration_date").prop("disabled", false);
        else{
            $("#id_lease_expiration_date").prop("disabled", true);
            $("#id_lease_expiration_date").val('');
        }
    });

    $("form").submit(function(){
        var re = true;
        if(!$("#id_display_number").prop("disabled") || $("#id_display_size").val()){
            if(!$("#id_display_number").val()){
                $("#id_display_number").parent().parent().addClass("has-error");
                $("#jqueryadd_1").remove();
                $("#id_display_number").after('<span class="help-block" id="jqueryadd_1" >このフィールドは必須です。</span>');
                re = false;
            }
        }
        if(!$("#id_lease_expiration_date").prop("disabled")){
            if(!$("#id_lease_expiration_date").val()){
                $("#id_lease_expiration_date").parent().parent().addClass("has-error");
                $("#jqueryadd_2").remove();
                $("#id_lease_expiration_date").after('<span class="help-block" id="jqueryadd_2" >このフィールドは必須です。</span>');
                re = false;
            }
        }
        return re;
    })

});
</script>
{% endblock %}

{% block content %}
    <h3 class="page-header">PCの編集</h3>
    {% if pc_id and isCopy %}
    <form action="{% url 'cms:pc_mod' pc_id=pc_id %}?copy=1" method="post" class="form-horizontal" role="form">
    {% elif pc_id %}
    <form action="{% url 'cms:pc_mod' pc_id=pc_id %}" method="post" class="form-horizontal" role="form">
    {% else %}
    <form action="{% url 'cms:pc_add' %}" method="post" class="form-horizontal" role="form">
    {% endif %}
      {% csrf_token %}
      {{ form|bootstrap_horizontal }}
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <button type="submit" class="btn btn-primary">送信</button>
        </div>
      </div>
    </form>
    <a href="{% url 'cms:pc_list' %}" class="btn btn-default btn-sm">戻る</a>
{% endblock content %}

cms/templates/cms/pc_list.html
{% extends "base_nav.html" %}
{% load bootstrap %}
{% load filters %}
{% load staticfiles %}

{% block title %}PCの一覧{% endblock title %}

{% block extrahead %}
<link href="{% static 'css/jquery-ui.min.css' %}" rel="stylesheet">
<script src="{% static 'js/jquery-ui.min.js' %}"></script>
<script src="{% static 'js/jquery.tablesorter.min.js' %}"></script>
<style>
table {
  margin-top: 8px;
  margin-bottom: 0px !important;
}
table th, table td {
    white-space: nowrap;
}
</style>
{% if user.is_staff %}
<script>
$(function(){
  // テーブル並び替え
  $('#sortable tbody').sortable({
    update: function(){
      data = $('#sortable tbody').sortable("serialize");
      $.ajax({
        type: "GET",
        url: "{% url 'cms:save_sort' %}",
        data: data,
        dataType: 'json'
      }).done(function(data) {
        for(id in data){
          $('#ids-'+id+' .sort_no').text(data[id]);
        }
      }).fail(function() {
        alert('ソートの保存に失敗しました。');
      });
    }
  });
  // テーブルソート
  $("#sortable").tablesorter();
  $(".del").on('click', function(){
    if(window.confirm("削除しますがよろしいですか？")) {
      return true;
    } else {
      return false;
    }
  });

  $('#upload_confiam').on('click', function () {
     $('#upload_url').attr('href', $(this).attr("url"));
  });

  $('#upload_exec').on('click', function () {
    if (!$('#id_file').prop('files')[0]) {
      alert('ファイルが選択されていません。');
      return false;
    }

    var fileName = $('#id_file').prop('files')[0].name;
    var type = fileName.split('.');
    if (type[type.length - 1].toLowerCase() == 'xls') {
      return true;
    }else{
      alert('xls拡張子のファイルではありません。');
      return false;
    }
  });
});
</script>
{% endif %}
{% endblock %}

{% block content %}
    <h3 class="page-header">PCの一覧</h3>
    {% if user.is_staff %}
    <a href="{% url 'cms:pc_add' %}" class="btn btn-default btn-sm">追加</a>
    <a href="{% url 'cms:download' %}" class="btn btn-default btn-sm">ダウンロード</a>
    <button class="btn btn-default btn-sm" id="upload_confiam" data-toggle="modal" data-target="#uploadModal" url="{% url 'cms:upload' %}">アップロード</button>
    {% endif %}
    <div style="overflow: scroll;">
    <table class="table table-striped table-bordered" id="sortable">
      <thead>
        <tr>
          <th>ソートNo</th>
          <th>使用者</th>
          <th>種類</th>
          <th>資産種類</th>
          <th>PC機器番号</th>
          <th>IPアドレス</th>
          <th>メーカー</th>
          <th>ディスプレイ - サイズ</th>
          <th>ディスプレイ - 機器番号</th>
          <th>キーボード - 機器番号</th>
          <th>マウス - 機器番号</th>
          <th>OS</th>
          <th>CPU</th>
          <th>HDD容量</th>
          <th>メモリ容量</th>
          <th>メディアドライブ</th>
          <th>リース期限日</th>
          <th>備考</th>
          <th style="width:8%">操作</th>
        </tr>
      </thead>
      <tbody>
        {% for pc in pc_list %}
        {% if pc.asset_class ==  1 %}
        <tr class="info">
        {% else %}
        <tr id="ids-{{ pc.id }}">
        {% endif %}
          <td class="sort_no">{{ pc.sort_no }}</td>
          <td>{{ pc.user }}</td>
          <td>{{ pc.get_machine_type_display }}</td>
          <td>{{ pc.get_asset_class_display }}</td>
          <td>{{ pc.pc_number }}</td>
          <td>{{ pc.ip_address|default_if_none:"" }}</td>
          <td>{{ pc.maker }}</td>
          <td>{{ pc.display_size }}</td>
          <td>{{ pc.display_number|default_if_none:"" }}</td>
          <td>{{ pc.keyboard_number|default_if_none:"" }}</td>
          <td>{{ pc.mouth_number|default_if_none:"" }}</td>
          <td>{{ pc.os }}</td>
          <td>{{ pc.cpu }}</td>
          <td>{{ pc.hdd_storage }}</td>
          <td>{{ pc.memory_storage }}</td>
          <td>{{ pc.media_drive }}</td>
          <td>{{ pc.lease_expiration_date|default_if_none:"" }}</td>
          {% if pc.remarks|length > 20 %}
          <td>{{ pc.remarks|truncate:10|cutmark }}</td>
          {% else %}
          <td>{{ pc.remarks }}</td>
          {% endif %}
          <td>
            <div class="btn-toolbar" style="width:230px;">
              <div class="btn-group">
                <a href="{% url 'cms:pc_detail' pc_id=pc.id %}" class="btn btn-default btn-info">詳細</a>
                {% if user.is_staff %}
                <a href="{% url 'cms:pc_mod' pc_id=pc.id %}" class="btn btn-default btn-warning">修正</a>
                <a href="{% url 'cms:pc_mod' pc_id=pc.id %}?copy=1" class="btn btn-default btn-success">複製</a>
                <a href="{% url 'cms:pc_del' pc_id=pc.id %}" class="btn btn-default btn-danger del">削除</a>
                {% endif %}
              </div>
            </div>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    </div>
{% if user.is_staff %}
<div class="modal fade" id="uploadModal" tabindex="-1" role="dialog" aria-labelledby="uploadModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title" >エクセルファイルのアップロード</h4>
      </div>
      <form action="{% url 'cms:upload' %}" method="post" class="form-horizontal" role="form" enctype="multipart/form-data">
        <div class="modal-body">
            {% csrf_token %}
            {{ upload_form|bootstrap_horizontal }}
             <p>※ファイルはExcelのxls拡張子のみ対応。尚一行目は無視されます。</p>
        </div>
        <div class="modal-footer">
          <button type="submit" class="btn btn-primary" id="upload_exec">アップロード</button>
          <button type="button" class="btn btn-default" data-dismiss="modal">キャンセル</button>
        </div>
      </form>
    </div>
  </div>
</div>
{% endif %}
{% endblock content %}